
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '8B5E0538ACB83BB8D90235FDEDE543BD'
    
_lr_action_items = {'STAR':([2,4,5,7,9,11,],[-7,-8,9,9,-6,-5,]),'$end':([1,2,4,5,6,7,9,11,12,],[-2,-7,-8,-4,0,-3,-6,-5,-1,]),'PLUS':([1,2,4,5,6,7,8,9,11,12,],[-2,-7,-8,-4,10,-3,10,-6,-5,-1,]),'LPAREN':([0,1,2,3,4,5,7,9,10,11,],[3,3,-7,3,-8,-4,-3,-6,3,-5,]),'CHAR':([0,1,2,3,4,5,7,9,10,11,],[4,4,-7,4,-8,-4,-3,-6,4,-5,]),'EMPTY':([0,1,2,3,4,5,7,9,10,11,],[2,2,-7,2,-8,-4,-3,-6,2,-5,]),'RPAREN':([1,2,4,5,7,8,9,11,12,],[-2,-7,-8,-4,-3,11,-6,-5,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'term':([0,3,10,],[1,1,1,]),'factor':([0,1,3,10,],[5,7,5,5,]),'expression':([0,3,10,],[6,8,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS expression','expression',3,'p_expression','main-project#3.py',43),
  ('expression -> term','expression',1,'p_expression_term','main-project#3.py',48),
  ('term -> term factor','term',2,'p_term','main-project#3.py',53),
  ('term -> factor','term',1,'p_term_factor','main-project#3.py',58),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_paren','main-project#3.py',63),
  ('factor -> factor STAR','factor',2,'p_factor_star','main-project#3.py',68),
  ('factor -> EMPTY','factor',1,'p_factor_empty','main-project#3.py',73),
  ('factor -> CHAR','factor',1,'p_factor','main-project#3.py',78),
]
