
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '8B5E0538ACB83BB8D90235FDEDE543BD'
    
_lr_action_items = {'STAR':([3,4,6,8,9,12,],[9,-7,-8,9,-6,-5,]),'$end':([1,2,3,4,6,8,9,11,12,],[0,-2,-4,-7,-8,-3,-6,-1,-5,]),'CHAR':([0,2,3,4,5,6,7,8,9,12,],[6,6,-4,-7,6,-8,6,-3,-6,-5,]),'RPAREN':([2,3,4,6,8,9,10,11,12,],[-2,-4,-7,-8,-3,-6,12,-1,-5,]),'PLUS':([1,2,3,4,6,8,9,10,11,12,],[7,-2,-4,-7,-8,-3,-6,7,-1,-5,]),'EMPTY':([0,2,3,4,5,6,7,8,9,12,],[4,4,-4,-7,4,-8,4,-3,-6,-5,]),'LPAREN':([0,2,3,4,5,6,7,8,9,12,],[5,5,-4,-7,5,-8,5,-3,-6,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,5,7,],[1,10,11,]),'term':([0,5,7,],[2,2,2,]),'factor':([0,2,5,7,],[3,8,3,3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS expression','expression',3,'p_expression','main-project#2.py',43),
  ('expression -> term','expression',1,'p_expression_term','main-project#2.py',48),
  ('term -> term factor','term',2,'p_term','main-project#2.py',53),
  ('term -> factor','term',1,'p_term_factor','main-project#2.py',58),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_paren','main-project#2.py',63),
  ('factor -> factor STAR','factor',2,'p_factor_star','main-project#2.py',68),
  ('factor -> EMPTY','factor',1,'p_factor_empty','main-project#2.py',73),
  ('factor -> CHAR','factor',1,'p_factor','main-project#2.py',78),
]
